apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: my-db-secret-test
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: my-db-secret-test